[package]
name = "dni-header-util"
version = "0.1.0"
authors = ["Andrii Dmytrenko <refresh.xss@gmail.com>"]
edition = "2018"
license = "BSD"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3"
structopt = "0.3"
